library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name="books"

urlpatterns = [
    path('',views.home,name="home"),
    path('view',views.viewbooks,name="view"),
    path('add',views.addbooks,name="add"),
    path('details/<int:p>',views.details,name="details"),
    path('edit/<int:p>',views.edit,name="edit"),
    path('delete/<int:p>',views.delete,name="delete"),
    path('search',views.search,name="search"),
    # path('admin/', admin.site.urls),

]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('users/',include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
app_name="users"

urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.userlogin,name="login"),
    path('logout',views.userlogout,name="logout"),
    # path('search',views.search,name="search"),

    # path('admin/', admin.site.urls),
]

library/books/models.py
from django.db import models


class Book(models.Model):          #database model defintion
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    language = models.CharField(max_length=20)
    price = models.IntegerField()
    pages = models.IntegerField()
    cover = models.ImageField(upload_to="images")
    pdf = models.FileField(upload_to="pdf")

library/users/models.py
from django.db import models

# Create your models here.

library/books/views.py
from django.db.models import Q
from django.shortcuts import render,redirect
from books.models import Book
from django.contrib.auth.decorators import login_required
# Create your views here.
def home(request):
    return render(request,'home.html')

@login_required
def addbooks(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        pa=request.POST['pa']
        l=request.POST['l']
        c=request.FILES['c']
        pd=request.FILES['pd']
        b=Book.objects.create(title=t,author=a,pages=pa,price=p,language=l,cover=c,pdf=pd)      #creates a new record
        b.save()
        return redirect('books:view')#save the records inside the table book
    return render(request,'add.html')
@login_required
def viewbooks(request):
    k=Book.objects.all()  #Reads all records from table Book.
    context={'book':k}      #passes data from views to html file.context is dictionary type.
    return render(request,'view.html',context)

def details(request,p):
    b=Book.objects.get(id=p)
    context={'book':b}
    return render(request,'details.html',context)

def edit(request,p):
    b=Book.objects.get(id=p)
    if (request.method == "POST"):
        b.title=request.POST['t']
        b.author=request.POST['a']
        b.price=request.POST['p']
        b.pages=request.POST['pa']
        b.language=request.POST['l']
        if(request.FILES.get('c')==None):
            b.save()
        else:
            b.cover=request.FILES.get('c')
        if(request.FILES.get('pd')==None):
            b.save()
        else:
            b.pdf=request.FILES.get('pd')

        b.save()
        return redirect('books:view')
    context={'book':b}
    return render(request,'edit.html',context)

def delete(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return redirect('books:view')

def search(request):
    b=None
    if(request.method=="POST"):
        print("hello")
        query=request.POST['q']
        print(query)
        if query:
            b=Book.objects.filter(Q(title=query) | Q(author=query))
    return render(request,"search.html",{'book':b})

library/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
def register(request):
    if(request.method=="POST"):
        u = request.POST['u']         #username
        p = request.POST['p']         #password
        cp = request.POST['cp']     #confirm password
        e = request.POST['e']              #email
        f = request.POST['f']             #firstname
        l = request.POST['l']                #lastname
        if(p==cp):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)       #create user is compliment here
            u.save()
        else:
            return HttpResponse(request,"PASSWORD SHOULD BE SAME")
        return redirect('books:home')
    return render(request,'register.html')

from django.contrib.auth import login,authenticate,logout
from django.http import HttpResponse
def userlogin(request):
    if(request.method=='POST'):
        u = request.POST['u']
        p = request.POST['p']
        user = authenticate(username=u,password=p)        #checks whether the details entered by user is correct or not
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("INVALID USER")
    return render(request,"login.html")

def userlogout(request):
    logout(request)
    return redirect('users:login')

# def search(request):
#     return render(request,"search.html")

library/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">ADD PAGE</h2>
<div class="container mt-3"></div>
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control"   name="t" placeholder="Enter the title">
</div>
    <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the author">
</div>
    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the language">
</div>
    <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the price">
</div>
    <div class="mb-3">
  <label class="form-label">Pages</label>
  <input type="number" class="form-control" name="pa" placeholder="Enter the pages">
</div>
     <div class="mb-3">
  <label class="form-label">Cover</label>
  <input type="file" class="form-control" name="c">
</div>
    <div class="mb-3">
  <label class="form-label">Pdf</label>
  <input type="file" class="form-control" name="pd">
</div>
    <div class="mb-3">
  <input type="submit" class="btn btn-dark text-light px-4">

</div>
</form>
{% endblock %}

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title><link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body style="">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>

        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:add' %}">Add books</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'books:view' %}">view books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">log out</a>
        </li>
        {% else %}

          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">log out</a>
        </li>

        {% endif %}

      </ul>
      {% if user.is_authenticated %}
      <form class="d-flex" method="POST" action="{% url 'books:search' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% endif %}
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<h1>welcome to home page</h1>
</body>
</html>

library/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">DETAIL</h3>
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{book.cover.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{book.title}}</h5>
        <p class="card-text">{{book.language}}</p>
           <p class="card-text">{{book.author}}</p>
           <p class="card-text">{{book.price}}</p>
           <p class="card-text">{{book.pages}}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

library/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">EDIT</h3>
<div class="container mt-3"></div>
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
  <label  class="form-label">Title</label>
  <input type="text" class="form-control"   name="t" value="{{book.title}}" placeholder="Enter the title">
</div>
    <div class="mb-3">
  <label  class="form-label">Author</label>
  <input type="text" class="form-control" name="a" value="{{book.author}}" placeholder="Enter the author">
</div>
    <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" value="{{book.language}}" placeholder="Enter the language">
</div>
    <div class="mb-3">
  <label class="form-label">Price</label>
  <input type="number" class="form-control" name="p" value="{{book.price}}" placeholder="Enter the price">
</div>
    <div class="mb-3">
  <label class="form-label">Pages</label>
  <input type="number" class="form-control" name="pa" value="{{book.pages}}" placeholder="Enter the pages">
</div>
     <div class="mb-3">
         <img src="{{book.cover.url}}" height="100px" width="100px">
  <label class="form-label">Cover</label>
  <input type="file" class="form-control" name="c">
</div>
    <div class="mb-3">
        <a href="{{book.pdf.url}}">{{book.pdf}}</a>
  <label class="form-label">Pdf</label>
  <input type="file" class="form-control" name="pd">
</div>
    <div class="mb-3">
  <input type="submit" class="btn btn-dark text-light px-4">

</div>
</form>
{% endblock %}

library/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">HOME</h3>
{% if user.is_authenticated %}
<h5 style="text-align:center;color:blue;">WELCOME {{user.username}}</h5>
{% else %}
        <h5 style="text-align:center;color:blue;">GUEST</h5>
{% endif %}
{% endblock %}

<!--<!DOCTYPE html>-->
<!--{% load static %}-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title><link rel="stylesheet" href="{% static 'css/style.css' %}">-->
<!--</head>-->
<!--<body style="background-image:url('{% static "images/boo.jpeg"%}')">-->
<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--  <div class="container-fluid">-->
<!--    <a class="navbar-brand" href="#">Library</a>-->
<!--    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--      <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--      <ul class="navbar-nav me-auto mb-2 mb-lg-0">-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="{% url 'books:home' %}">Home</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'books:add' %}">Add books</a>-->
<!--        </li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'books:view' %}">view books</a>-->
<!--        </li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'users:register' %}">Register</a>-->
<!--        </li>-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'users:login' %}">Login</a>-->
<!--        </li>-->
<!--      </ul>-->
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->
<!--<h1>welcome to home page new</h1>-->
<!--<h1>welcome to home page</h1>-->
<!--</body>-->
<!--</html>-->

library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">LOGIN</h3>
<div class="container"><form style="color:white" method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label class="form-label">USER NAME</label>
        <input type="text" class="form-control" name="u" placeholder="ENTER YOUR USER NAME">
  </div>
    <div class="mb-3">
        <label class="form-label">PASSWORD</label>
    <input type="password" class="form-control" NAME="p" placeholder="ENTER YOUR PASSWORD">
    </div>
<button type="submit" class="btn btn-secondary">SUBMIT</button>
</form>
    </div>
{% endblock %}

library/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">REGISTER</h3>
<div class="container"><form style="color:white" method="POST" >
    {% csrf_token %}
    <div class="mb-3">
    <label  class="form-label">USER NAME</label>
    <input type="text" class="form-control" name="u" placeholder="ENTER YOUR USERNAME">
  </div>
    <div class="mb-3">
    <label  class="form-label">PASSWORD</label>
        <input type="password" class="form-control" name="p" placeholder="ENTER YOUR PASSWORD">
  </div>
    <div class="mb-3">
    <label  class="form-label">CONFIRM PASSWORD</label>
        <input type="password" class="form-control" name="cp" placeholder="ENTER YOUR PASSWORD AGIN">
  </div>
    <div class="mb-3">
    <label  class="form-label">E-MAIL</label>
        <input type="email" class="form-control" name="e" placeholder="ENTER YOUR EMAIL">
  </div>
    <div class="mb-3">
    <label  class="form-label">FIRST NAME</label>
        <input type="text" class="form-control" name="f" placeholder="ENTER YOUR FIRSTNAME">
  </div>
    <div class="mb-3">
    <label  class="form-label">LAST NAME</label>
    <input type="text" class="form-control" name="l" placeholder="ENTER YOUR LASTNAME">  </div>

<button type="submit" class="btn btn-primary">SUBMIT</button></form>
    </div>
{% endblock %}

library/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">SEARCH RESULTS</h3>
{{book}}
<div class="container mt-5 p-5">
    <h1 class="text-center">YOU HAVE SEARCHED FOR <span class="text-light">{{query}}</span></h1>
    <div class="mx-auto w-75">
        {% if book == None %}
        <h4 class="text-center text-danger">NO RESULTS FOUND</h4>
        {% elif book.exists %}

        <table class="table table-bordered">
            <tr>BOOK RESULTS</tr>
        </table>

        {% else %}
        <h4 class="text-center text-danger">NO RESULTS FOUND</h4>
        {% endif %}
    </div>
</div>
{% endblock %}

library/templates/view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title><link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<h1>view the page</h1>
<table class="table table-bordered w-75 mx-auto mt-48u">
    <tr class="fw-bold fs-4">
<!--        <th>Cover</th>-->
        <th>Title</th>
        <th>Author</th>
        <th>Language</th>
        <th>Price</th>
        <th>page</th>
         <th>Cover</th>
        <th>pdf</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
<!--{% for i in book %}-->
    <tr>

        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.language}}</td>
        <td>{{i.price}}</td>
        <td>{{i.pages}}</td>
<!--        <td><img src="{{i.cover.url}}"></td>-->
        <td><img src="{{i.cover.url}}" height="150px" width="100px" class="img-thumbnail"></td>
        <td><a href="{{i.pdf.url}}">Download</a></td>
        <td><a href="{% url 'books:details' i.id %}" class="btn btn-secondary text-light">View</a></td>
        <td><a href="{% url 'books:edit' i.id %}" class="btn btn-secondary text-light">Edit</a></td>
        <td><a href="{% url 'books:delete' i.id %}" class="btn btn-secondary text-light">Delete</a></td>
    </tr>
<!--    {% endfor %}-->
<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>Book details</li>-->
<!--    <ul>-->
<!--        <li>Title:{{i.title}}</li>-->
<!--        <li>Author:{{i.author}}</li>-->
<!--        <li>Languages:{{i.language}}</li>-->
<!--        <li>Price:{{i.price}}</li>-->
<!--        <li>Pages:{{i.pages}}</li>-->
<!--        <li>Cover:{{i.cover}}</li>-->
<!--        <li>pdf:{{i.pdf}}</li>-->
<!--    </ul>-->
<!--    {% endfor %}-->
<!--</ol>-->

</table>
</body>
</html>