Design2/Design2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Design2/cart/urls.py
from django.conf.urls.static import static
from django.conf import settings
from cart import views
from django.urls import path
app_name="cart"


urlpatterns = [
    path('addtocart/<int:i>', views.addtocart, name='addtocart'),
    path('cart_view', views.cart_view, name='cart_view'),
    path('cart_remove/<int:i>', views.cart_remove, name='cart_remove'),
    path('Orderform', views.Orderform, name='Orderform'),
    path('paymentstatus/<str:p>', views.payment_status, name='paymentstatus'),
    path('vieworder',views.vieworder,name="vieworder"),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Design2/search/urls.py
from django.conf.urls.static import static
from django.conf import settings
from search import views
from django.urls import path
app_name="search"


urlpatterns = [
    path('searchview/',views.searchview,name="searchview")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Design2/shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from shop import views
from django.urls import path
app_name="shop"


urlpatterns = [
    path('', views.Home, name='Home'),
    path('products/<int:i>',views.Products,name='products'),
    path('detail/<int:i>',views.ProductDetail,name='detail'),
    path('u_login',views.u_login,name='login'),
    path('register',views.register,name='register'),
    path('u_logout',views.u_logout,name='logout'),
    path('addcategories',views.addcategories,name='addcategories'),
    path('addproducts',views.addproducts,name='addproducts'),
    path('addstock/<int:i>', views.addstock, name='addstock'),




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Design2/cart/models.py
from django.db import models

from shop.models import Product
from django.contrib.auth.models import User
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.product.price*self.quantity

    def __str__(self):
        return self.product.name
class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField(max_length=100)
    phone=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=20)
    payment_status=models.CharField(max_length=20)
    delivery_status=models.CharField(max_length=20)
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.order_id
class Payment(models.Model):
    name=models.CharField(max_length=20)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=20)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.order_id

Design2/cart/views.py
from django.shortcuts import render,redirect
from cart.models import Cart,Payment,Order_details
from shop.models import Product
import razorpay
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:
        c=Cart.objects.get(user=u,product=p)
        c.quantity+=1
        p.stock-=1
        p.save()
        c.save()
    except:
        c=Cart.objects.create(product=p,user=u,quantity=1)
        p.stock -= 1
        p.save()
        c.save()


    return redirect('cart:cart_view')
def cart_view(request):
    u=request.user
    c=Cart.objects.filter(user=u)
    total=0
    for i in c:
        total+=i.quantity*i.product.price
    context = {'cart': c,'total':total}
    return render(request,'cart.html',context)
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    c=Cart.objects.get(user=u,product=p)
    if(c.quantity > 1):
        c.quantity-=1
        c.save()
        p.stock+=1
        p.save()
    else:
        c.delete()
        p.stock+=1
        p.save()
    return redirect('cart:cart_view')

def cart_fullremove(request,i):
    p = Product.objects.get(id=i)
    u = request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        c.delete()
        p.stock += c.quantity
        p.save()
    except:
        pass
def Orderform(request):
    if request.method=="POST":
        #Read input from the form fields
        a=request.POST['a']
        ph=request.POST['ph']
        n=request.POST['n']

        #for calculating total bill amount
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.product.price*i.quantity
        print(total)

        #Razorpay client connection
        client=razorpay.Client(auth=('rzp_test_erK40pETfxlgk0','013NJEwDvmB1zLK5d2HzMEgg'))
        #Razorpay order creation
        response_payment=client.order.create(dict(amount=total*100,currency='INR'))
        order_id=response_payment['id'] #retrieve the order id from response
        status=response_payment['status'] #retrieve the status from response


        if (status=="created"):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()

            for i in c:
                o=Order_details.objects.create(product=i.product,user=i.user,phone=ph,address=a,pin=n,order_id=order_id,no_of_items=i.quantity)
                o.save()

            context={'payment':response_payment,'name':u.username} #sends the response from view to payment.html

            return render(request,"payment1.html",context)

    return render(request,'Orderform.html')



from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.contrib.auth import login
@csrf_exempt
def payment_status(request,p):
    user=User.objects.get(username=p) #retrieve user object
    login(request,user)

    response=request.POST #razorpay response after successful payment
    print(response)


    #To Check the validity(authenticity) of razorpay payment details received by application
    param_dict={
        'razorpay_order_id':response['razorpay_order_id'],
        'razorpay_payment_id':response['razorpay_payment_id'],
        'razorpay_signature':response['razorpay_signature']
        }

    client = razorpay.Client(auth=('rzp_test_erK40pETfxlgk0', '013NJEwDvmB1zLK5d2HzMEgg'))
    try:
        status=client.utility.verify_payment_signature(param_dict)   #for checking the payment details
                                                                       # we pass param_dict to verify_payment_signature function
        print(status)

        p=Payment.objects.get(order_id=response['razorpay_order_id'])  #After successful payment retrieve the payment record matching with response['order_id]
        p.razorpay_payment_id=response['razorpay_payment_id']  #assigns response [payment id] to razorpay_payment_id
        p.paid=True   #assigns paid value to true
        p.save()


        o=Order_details.objects.filter(order_id=response['razorpay_order_id']) #After successful payment retrieve the order_details records matching with response['order_id]
        for i in o:
            i.payment_status="completed"   #assigns "completed" to payment_status in each record
            i.save()


    except:
        pass
    return render(request,'Payment.html')

def vieworder(request):
    u=request.user
    o=Order_details.objects.filter(user=u,payment_status="completed")
    context={'orders':o}
    return render(request,'vieworder.html',context)

Design2/search/views.py
from django.db.models import Q
from django.shortcuts import render
from shop.models import Product


def searchview(request):
    p=None
    query=""
    if(request.method=="POST"):
        query=request.POST['s']
        if query:
            p=Product.objects.filter(Q(name__icontains=query)|Q(price__icontains=query))

    return render(request,'search.html',{'Product':p,'query':query})

Design2/templates/Addcategory.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 style="text-align:center;color:blue;">ADD CATEGORY DETAILS</h1>
<div class="container">
    <form  method="post">
    {% csrf_token %}
        <div class="mb-3">
    <label class="form-label">CATEGORY NAME</label>
    <input type="text" class="form-control" name="n" placeholder="ENTER CATEGORY NAME">
  </div>
    <div class="mb-3">
    <label class="form-label">IMAGE</label>
        <input type="file" class="form-control" name="i" >
  </div>
    <div class="mb-3">
    <label class="form-label">DESCRIPTION</label>
        <textarea class="form-control" name="d" ></textarea>
  </div>
<button type="submit" class="btn btn-secondary ">Submit</button>
    </form>
</div>
{% endblock %}

Design2/templates/Payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">PAYMENT SUCCESSFULL</h2>
{% endblock %}

Design2/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
<h2 style="text-align:center;color:blue">SHOPPING CART</h2>
<div class="container" style="color:white">

  <table class="table table-bordered">
    <tr>
        <th scope="col">PRODUCT IMAGE</th>
        <th scope="col">PRODUCT NAME</th>
        <th scope="col">PRODUCT PRICE</th>
        <th scope="col">PRODUCT QUANTITY</th>
        <th scope="col">SUBTOTAL</th>
        <th scope="col">TOTAL</th>
        <th scope="col">EDIT</th>


    </tr>
{% for i in cart %}
    <tr>
        <td><img src="{{i.product.image.url}}" height="200px" width="100%"></td>
        <td>{{i.product.name}}</td>
        <td>{{i.product.price}}</td>
        <td>{{i.quantity}}</td>
        <td>Subtotal:{{i.subtotal}}</td>
        <td>Total:{{total}}</td>
        <td style="align-content:space-between">
            {% if i.product.stock > 0 %}
                <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-minus"></i></a>
                <a href=""><i class="fa-solid fa-trash"></i></a>
            {% else %}
                  <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-minus"></i></a>
                  <a href=""><i class="fa-solid fa-trash"></i></a>
            {% endif %}

           </td>

    </tr>
    {% endfor %}
  </table>
    <a href="{% url 'cart:Orderform' %}" class="btn btn-danger">Place Order</a>
    <a href="{% url 'shop:Home' %}" class="btn btn-danger">Continue Shopping</a>

{% endblock %}

Design2/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="collection bg-light position-relative py-5">
    <div class="container">
      <div class="row">
        <div class="title-xlarge text-uppercase txt-fx domino">Collection</div>
        <div class="collection-item d-flex flex-wrap my-5">
          <div class="col-md-6 column-container">
            <div class="image-holder">
              <img src="{{pro.image.url}}" alt="collection"  class="product-image img-fluid">
            </div>
          </div>
          <div class="col-md-6 column-container bg-white">
            <div class="collection-content p-5 m-0 m-md-5">
              <h3 class="element-title text-uppercase">{{pro.name}}</h3>
              <p>Dignissim lacus, turpis ut suspendisse vel tellus. Turpis purus, gravida orci, fringilla a. Ac sed eu
                fringilla odio mi. Consequat pharetra at magna imperdiet cursus ac faucibus sit libero. Ultricies quam
                nunc, lorem sit lorem urna, pretium aliquam ut. In vel, quis donec dolor id in. Pulvinar commodo mollis
                diam sed facilisis at cursus imperdiet cursus ac faucibus sit faucibus sit libero.</p>
              <p>{{pro.stock}}</p>
              <p>{{pro.price}}</p>

              {% if user.is_superuser %}
                {% if pro.stock > 0 %}
                  <p>Product in Stock</p>
                  <a href="{% url 'shop:addstock' pro.id %}" class="btn btn-dark text-uppercase mt-3">Add Stock</a>
                {% else %}
                  <p>Product is Out of Stock</p>
                  <a href="{% url 'shop:addstock' pro.id %}" class="btn btn-dark text-uppercase mt-3">Add Stock</a>
                {% endif %}
              {% else %}
                {% if pro.stock > 0 %}
                  <p>Product in Stock</p>
                  <a href="{% url 'cart:addtocart' pro.id %}" class="btn btn-dark text-uppercase mt-3">Add to Cart</a>
                {% else %}
                  <a href="#" class="btn btn-dark text-uppercase mt-3">Out of Stock</a>
                {% endif %}
              {% endif %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

Design2/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <section id="billboard" class="bg-light py-5">
    <div class="container">
      <div class="row justify-content-center">
        <h1 class="section-title text-center mt-4" data-aos="fade-up">New Collections</h1>
        <div class="col-md-6 text-center" data-aos="fade-up" data-aos-delay="300">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptas ut dolorum consequuntur, adipisci
            repellat! Eveniet commodi voluptatem voluptate, eum minima, in suscipit explicabo voluptatibus harum,
            quibusdam ex repellat eaque!</p>
        </div>
      </div>
      <div class="row">
        <div class="swiper main-swiper py-4" data-aos="fade-up" data-aos-delay="600">
          <div class="swiper-wrapper d-flex border-animation-left">
            <div class="swiper-slide">
              <div class="banner-item image-zoom-effect">
                <div class="image-holder">
                  <a href="#">
                    <img src="{% static 'images/banner-image-6.jpg' %}" alt="product" class="img-fluid">
                  </a>
                </div>
                <div class="banner-content py-4">
                  <h5 class="element-title text-uppercase">
                    <a href="index.html" class="item-anchor">Soft leather jackets</a>
                  </h5>
                  <p>Scelerisque duis aliquam qui lorem ipsum dolor amet, consectetur adipiscing elit.</p>
                  <div class="btn-left">
                    <a href="#" class="btn-link fs-6 text-uppercase item-anchor text-decoration-none">Discover Now</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="banner-item image-zoom-effect">
                <div class="image-holder">
                  <a href="#">
                    <img src="{% static 'images/banner-image-1.jpg' %}" alt="product" class="img-fluid">
                  </a>
                </div>
                <div class="banner-content py-4">
                  <h5 class="element-title text-uppercase">
                    <a href="index.html" class="item-anchor">Soft leather jackets</a>
                  </h5>
                  <p>Scelerisque duis aliquam qui lorem ipsum dolor amet, consectetur adipiscing elit.</p>
                  <div class="btn-left">
                    <a href="#" class="btn-link fs-6 text-uppercase item-anchor text-decoration-none">Discover Now</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="banner-item image-zoom-effect">
                <div class="image-holder">
                  <a href="#">
                    <img src="{% static 'images/banner-image-2.jpg' %}" alt="product" class="img-fluid">
                  </a>
                </div>
                <div class="banner-content py-4">
                  <h5 class="element-title text-uppercase">
                    <a href="index.html" class="item-anchor">Soft leather jackets</a>
                  </h5>
                  <p>Scelerisque duis aliquam qui lorem ipsum dolor amet, consectetur adipiscing elit.</p>
                  <div class="btn-left">
                    <a href="#" class="btn-link fs-6 text-uppercase item-anchor text-decoration-none">Discover Now</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="swiper-slide">
              <div class="banner-item image-zoom-effect">
                <div class="image-holder">
                  <a href="#">
                    <img src="{% static 'images/banner-image-3.jpg' %}" alt="product" class="img-fluid">
                  </a>
                </div>
              </section>

  <div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasCart" aria-labelledby="My Cart">
    <div class="offcanvas-header justify-content-center">
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-primary">Your cart</span>
          <span class="badge bg-primary rounded-pill">3</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Growers cider</h6>
              <small class="text-body-secondary">Brief description</small>
            </div>
            <span class="text-body-secondary">$12</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Fresh grapes</h6>
              <small class="text-body-secondary">Brief description</small>
            </div>
            <span class="text-body-secondary">$8</span>
          </li>
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">Heinz tomato ketchup</h6>
              <small class="text-body-secondary">Brief description</small>
            </div>
            <span class="text-body-secondary">$5</span>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>$20</strong>
          </li>
        </ul>

        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to Checkout</button>
      </div>
    </div>
  </div>


<div class="container w-50 mx-auto mt-5">




<h1 class="text-center" style="font-size:40px;">OUR COLLECTIONS</h1>
<P style="text-align:justify;line-height:2;font-size:15px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore omnis qui saepe. Aut consequatur doloremque
  laborum placeat quibusdam
  repudiandae sed! Dolore itaque laborum quibusdam ratione repudiandae similique soluta totam voluptatum!
Lorem ipsu labore maxime obcaecati, officiis sapiente, ullam vero vitae.  cum necessitatibus quos.
  Enim, totam.lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at commodi eaque sunt voluptates! Cum
  deserunt dolorem dolorum eligendi ex explicabo maiores molestiae nihil quaerat rem reprehenderit tenetur, ullam, voluptatum?Lorem ipsum dolor sit amet,
</P>

</div>


<!--CARD-->

  <section class="categories overflow-hidden">
    <div class="container">
      <div class="open-up" data-aos="zoom-out">

        <div class="row">
          {% for i in cat %}

          <div class="col-md-4">

            <div class="cat-item image-zoom-effect">
              <div class="image-holder">
                <a href="{% url 'shop:products' i.id %}">
                  <img src="{{i.image.url}}" alt="categories"  style="height:200px;width:300px">
                </a>
              </div>
              <div class="category-content">
                <div class="product-button">
                  <a href="{% url 'shop:products' i.id %}" class="btn btn-common text-uppercase">{{i.name}}</a>
                </div>
              </div>
            </div>

          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </section>

<!--CARD END-->

{% endblock %}

Design2/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container">
      <div class="row justify-content-center">
        <h1 class="section-title text-center mt-4" data-aos="fade-up">{{cat.name}}</h1>
        <div class="col-md-6 text-center" data-aos="fade-up" data-aos-delay="300">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptas ut dolorum consequuntur, adipisci
            repellat! Eveniet commodi voluptatem voluptate, eum minima, in suscipit explicabo voluptatibus harum,
            quibusdam ex repellat eaque!</p>
        </div>
      </div>

<div class="container-fluid">
    <img src="{{cat.image.url}}" height="800px" width="100%" >
</div>
 <section id="new-arrival" class="new-arrival product-carousel py-5 position-relative overflow-hidden">
     <div class="container">
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-5 mb-3">
          <h4 class="text-uppercase">Our New Arrivals</h4>
      </div>
      <div class="swiper product-swiper open-up" data-aos="zoom-out">
        <div class="swiper-wrapper d-flex">

<!--        <div class="swiper-wrapper d-flex">-->
<!--          <div class="swiper-slide">-->
<!--            <div class="product-item image-zoom-effect link-effect">-->
<!--              <div class="image-holder position-relative">-->
<!--                <a href="index.html">-->
<!--                  <img src="images/product-item-1.jpg" alt="categories" class="product-image img-fluid">-->
<!--                </a>-->
<!--                <a href="index.html" class="btn-icon btn-wishlist">-->
<!--                  <svg width="24" height="24" viewBox="0 0 24 24">-->
<!--                    <use xlink:href="#heart"></use>-->
<!--                  </svg>-->
<!--                </a>-->
<!--                <div class="product-content">-->
<!--                  <h5 class="element-title text-uppercase fs-5 mt-3">-->
<!--                    <a href="index.html">Dark florish onepiece</a>-->
<!--                  </h5>-->
<!--                  <a href="#" class="text-decoration-none" data-after="Add to cart"><span>$95.00</span></a>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="swiper-slide">-->
<!--            <div class="product-item image-zoom-effect link-effect">-->
<!--              <div class="image-holder position-relative">-->
<!--                <a href="index.html">-->
<!--                  <img src="images/product-item-2.jpg" alt="categories" class="product-image img-fluid">-->
<!--                </a>-->
<!--                <a href="index.html" class="btn-icon btn-wishlist">-->
<!--                  <svg width="24" height="24" viewBox="0 0 24 24">-->
<!--                    <use xlink:href="#heart"></use>-->
<!--                  </svg>-->
<!--                </a>-->
<!--                <div class="product-content">-->
<!--                  <h5 class="text-uppercase fs-5 mt-3">-->
<!--                    <a href="index.html">Baggy Shirt</a>-->
<!--                  </h5>-->
<!--                  <a href="#" class="text-decoration-none" data-after="Add to cart"><span>$55.00</span></a>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="swiper-slide">-->
<!--            <div class="product-item image-zoom-effect link-effect">-->
<!--              <div class="image-holder position-relative">-->
<!--                <a href="index.html">-->
<!--                  <img src="images/product-item-3.jpg" alt="categories" class="product-image img-fluid">-->
<!--                </a>-->
<!--                <a href="index.html" class="btn-icon btn-wishlist">-->
<!--                  <svg width="24" height="24" viewBox="0 0 24 24">-->
<!--                    <use xlink:href="#heart"></use>-->
<!--                  </svg>-->
<!--                </a>-->
<!--                <div class="product-content">-->
<!--                  <h5 class="text-uppercase fs-5 mt-3">-->
<!--                    <a href="index.html">Cotton off-white shirt</a>-->
<!--                  </h5>-->
<!--                  <a href="#" class="text-decoration-none" data-after="Add to cart"><span>$65.00</span></a>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
<!--          <div class="swiper-slide">-->
<!--            <div class="product-item image-zoom-effect link-effect">-->
<!--              <div class="image-holder position-relative">-->
<!--                <a href="index.html">-->
<!--                  <img src="images/product-item-4.jpg" alt="categories" class="product-image img-fluid">-->
<!--                </a>-->
<!--                <a href="index.html" class="btn-icon btn-wishlist">-->
<!--                  <svg width="24" height="24" viewBox="0 0 24 24">-->
<!--                    <use xlink:href="#heart"></use>-->
<!--                  </svg>-->
<!--                </a>-->
<!--                <div class="product-content">-->
<!--                  <h5 class="text-uppercase fs-5 mt-3">-->
<!--                    <a href="index.html">Crop sweater</a>-->
<!--                  </h5>-->
<!--                  <a href="#" class="text-decoration-none" data-after="Add to cart"><span>$50.00</span></a>-->
<!--                </div>-->
<!--              </div>-->
<!--            </div>-->
<!--          </div>-->
           {% for i in pro %}

            <div class="swiper-slide">

            <div class="product-item image-zoom-effect link-effect">
              <div class="image-holder position-relative">
                <a href="index.html">
                  <img src="{{i.image.url}}" style="height:300px;width:300px">
                </a>
                <a href="index.html" class="btn-icon btn-wishlist">
                    <svg width="24" height="24" viewBox="0 0 24 24">
                    <use xlink:href="#heart"></use>
                    </svg>
                </a>                <div class="product-content">
                  <h5 class="text-uppercase fs-5 mt-3">
                      <a href="index.html">{{i.name}}
                      </a>
                  </h5>
                  <a href="{% url 'shop:detail' i.id %}" class="text-decoration-none" data-after="View Details"><span>{{i.price}}</span></a>
                </div>
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
          <div class="swiper-pagination"></div>
      </div>
         <div class="icon-arrow icon-arrow-left"><svg width="50" height="50" viewBox="0 0 24 24">
          <use xlink:href="#arrow-left"></use>
         </svg>
         </div>
      <div class="icon-arrow icon-arrow-right">
          <svg width="50" height="50" viewBox="0 0 24 24">
          <use xlink:href="#arrow-right"></use>
        </svg>
      </div>
     </div>
  </section>
{% endblock %}

Design2/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 style="text-align:center;color:blue;">SEARCH</h1>

    <div class="card container">

      <form role="search" method="post" class="form-group" action="{% url 'search:searchview' %}">
          {% csrf_token %}
          <input type="search" id="search-form" class="form-control border-0 border-bottom" placeholder="Type and press enter" value="" name="s"/>
          <button type="submit" class="search-submit border-0 position-absolute bg-white" style="top: 15px;right: 15px;">
          <svg class="search" width="24" height="24">
          <use xlink:href="#search"></use>
          </svg></button>
      </form>
</div>
<div style="color:white" class="container">
<h1 class="text-center">YOU HAVE SEARCHED FOR <span class="text-light">{{query}}</span></h1>
<div class="mx-auto w-75">
    {% if Product == None %}
     <h4 class="text-center text-danger">NO RESULT FOUND</h4>
    {% elif Product.exists %}

     {% for i in Product %}
        <div class="col-md-6 column-container bg-danger">
            <div class="collection-content p-5 m-0 m-md-5">
                <img src="{{i.image.url}}" class="img-fluid rounded-start" height="200px" width="150px" alt="not">
              <h3 class="element-title text-uppercase">{{i.name}}</h3>
              <p>DESCRIPTION : {{i.desc}}</p>
                <p>PRICE :${{i.price}}</p>
              <p>STOCK : {{i.stock}}</p>
            </div>
 </div>
    {% endfor %}
    {% else %}
     <h4 class="text-center text-danger">NO RESULT FOUND</h4>
    {% endif %}
</div></div>

{% endblock %}